import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import { ApolloWrapper } from "@/lib/graphql";
import { AuthProvider } from "@/lib/auth/auth-context";
import { ServiceWorkerRegistration } from "@/components/pwa/service-worker-registration";
import { PushNotificationPrompt } from "@/components/pwa/push-notification-prompt";

/**
 * Inter font configuration
 * Using variable font for optimal performance and flexibility
 */
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

/**
 * Default metadata for the application
 * This is overridden per-page and per-tenant
 */
export const metadata: Metadata = {
  title: {
    default: process.env.NEXT_PUBLIC_APP_NAME || "My Hotel",
    template: `%s | ${process.env.NEXT_PUBLIC_APP_NAME || 'My Hotel'}`,
  },
  description:
    "Book your perfect stay. Browse rooms, check availability, and reserve online.",
  keywords: [
    "hotel",
    "booking",
    "rooms",
    "accommodation",
    "reservation",
  ],
  authors: [{ name: process.env.NEXT_PUBLIC_APP_NAME || "My Hotel" }],
  creator: process.env.NEXT_PUBLIC_APP_NAME || "My Hotel",
  publisher: process.env.NEXT_PUBLIC_APP_NAME || "My Hotel",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"
  ),
  openGraph: {
    type: "website",
    locale: "en_IN",
    siteName: process.env.NEXT_PUBLIC_APP_NAME || "My Hotel",
    title: process.env.NEXT_PUBLIC_APP_NAME || "My Hotel",
    description:
      "Book your perfect stay. Browse rooms, check availability, and reserve online.",
  },
  twitter: {
    card: "summary_large_image",
    title: process.env.NEXT_PUBLIC_APP_NAME || "My Hotel",
    description:
      "Book your perfect stay. Browse rooms, check availability, and reserve online.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

/**
 * Viewport configuration for mobile optimization
 */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
};

/**
 * Root Layout Component
 * 
 * This is the top-level layout that wraps all pages.
 * It sets up:
 * - Font configuration
 * - Global providers (toast notifications)
 * - HTML structure with proper lang attribute
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Preconnect to external resources for faster loading */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        {/* PWA manifest - auto-generated by Next.js from manifest.ts */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content={process.env.NEXT_PUBLIC_APP_NAME || "Hotel Manager"} />
        {/* Apple touch icon for iOS */}
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
      </head>
      <body
        className={`${inter.variable} font-sans antialiased min-h-screen bg-white`}
      >
        {/* Apollo GraphQL Provider */}
        <ApolloWrapper>
          {/* Auth Provider - manages user session */}
          <AuthProvider>
            {/* Main application content */}
            {children}
          </AuthProvider>
        </ApolloWrapper>

        {/* Toast notifications - positioned bottom-right on desktop, bottom on mobile */}
        <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              background: "white",
              border: "1px solid #e5e7eb",
              boxShadow:
                "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
            },
            className: "text-sm",
          }}
          richColors
          closeButton
        />

        {/* PWA service worker registration */}
        <ServiceWorkerRegistration />
        <PushNotificationPrompt />

        {/* Google Analytics */}
        {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
              strategy="afterInteractive"
            />
            <Script id="ga-init" strategy="afterInteractive">
              {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');`}
            </Script>
          </>
        )}

        {/* Google Tag Manager */}
        {process.env.NEXT_PUBLIC_GTM_ID && (
          <Script id="gtm-init" strategy="afterInteractive">
            {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${process.env.NEXT_PUBLIC_GTM_ID}');`}
          </Script>
        )}
      </body>
    </html>
  );
}
